extractor:
  name: sp_light
  num_kpt: 2000
  resize: [-1] 
  num_process: 4
  det_th: 0.0005

matcher:
  name: SG
  model_dir: weights/sg/sp  
  net_channels: 256
  layer_num: 9
  head: 4
  seedlayer: [0,4]
  use_score_encoding: True
  use_desc: True
  sink_iter: [20,80]
  p_th: 0.8
  addition_atten_layer_num: 0